name: Deploy to GitHub Pages
# Courtesy of - https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET 6 SDK
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.300

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish timeline.csproj -c Release -o ghpages --nologo
    
    # changes the base-tag in index.html from '/' to 'timeline' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to timeline
      run: sed -i 's/<base href="\/" \/>/<base href="\/timeline\/" \/>/g' ghpages/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp ghpages/wwwroot/index.html ghpages/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch ghpages/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ghpages/wwwroot
